jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.set-output-step.outputs.my_variable }}
    steps:
      - name: Set output variable
        id: set-output-step
        run: echo "my_variable=hello world" >> $GITHUB_ENV
