name: Multi-job Workflow

on:
  workflow_dispatch: # Allows manual trigger of the workflow
    inputs:
      custom_version: # Optional input for a custom version
        description: 'Custom version to publish (e.g., v1.2.3) -- only edit if you know what you are doing'
        required: false
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.set-output-step.outputs.my_variable }}
    steps:
      - name: Set output variable
        id: set-output-step
        run: echo "my_variable=${{ github.event.inputs.custom_version }}" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use output from job1
        run: echo "The value from job1 is ${{ needs.job1.outputs.my_output }}" 
      - name: Test logging secret
        run: echo "the secret value is ${{ secrets.TEST_SECRET }}"
