name: Trigger Workflow

on:
  workflow_dispatch: # Allows manual trigger of the workflow
    inputs:
      custom_version:
        description: 'Custom version to publish (e.g., v1.2.3)'
        required: false

jobs:
  compute-and-call:
    runs-on: ubuntu-latest
    outputs:
      secret_length: ${{ steps.compute_length.outputs.secret_length }}
    steps:
      - name: Compute secret length
        id: compute_length
        env:
          SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          secret_length=${#SECRET}
          echo "secret_length=$secret_length" >> $GITHUB_OUTPUT

  reusable-workflow:
    needs: compute-and-call
    uses: .github/workflows/reusable_workflow.yml@main
    with:
      secret_length: ${{ needs.compute-and-call.outputs.secret_length }}
